# .rubocop.yml  規則の緩和を目的とする記載

AllCops:
  DisabledByDefault: true
  NewCops: enable
  
inherit_from: .rubocop_todo.yml

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10

Style/FrozenStringLiteralComment:
  Enabled: false