version: '3'

services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/web
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tabilog_development
      SELENIUM_WEBDRIVER_URL: http://chrome:4444/wd/hub
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tabilog_development
    volumes:
      - db_data:/var/lib/postgresql/data
  chrome:
    image: seleniarm/standalone-chromium
    ports:
      - 4444:4444

volumes:
  db_data: