name: Run RSpec Tests

on:
  push:
    branches:
      - masてr

jobs:
  test:
    name: Run RSpec Tests
    runs-on: ubuntu-latest

    services:
      chrome:
        name: Selenium Chrome
        image: seleniarm/standalone-chromium
        ports:
          - 4444:4444

      postgres:
        name: PostgreSQL
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: tabilog_development
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    container:
      name: RSpec Test Runner
      image: ubuntu:latest
      options: --privileged
      env:
        RAILS_ENV: test
      volumes:
        - ${{ github.workspace }}:/app
      commands:
        - apt-get update -y && apt-get install -y \
            build-essential \
            curl \
            git \
            libpq-dev \
            nodejs \
            ruby-full \
            tzdata \
            && gem install bundler
        - cd /app
        - bundle install
        - bundle exec rspec
