name: Rails RSpec and security
on: [push, pull_request]
env:
  RAILS_ENV: test
  CI_HOST: localhost

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      chrome:
        image: selenium/standalone-chrome
        ports:
          - "4444:4444"
        volumes:
          - /dev/shm:/dev/shm

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0

      - name: Ruby Bundler
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: yarn install
        run: yarn install

      - uses: actions/cache@v2
        id: yarn-cache 
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup test database
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: |
          bundle exec rake db:create db:schema:load --trace

      - name: run rspec
        run: bundle exec rspec
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub

      - name: Archive rspec result screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: rspec result screenshots
          path: tmp/screenshots/

      # - name: security check
        # run: |
          # bundle exec bundle-audit check --update
          # bundle exec brakeman -q -w2

